version: "3.8"
services:

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.1
    container_name: filebeat
    volumes:
      - ./logs:/var/log/filebeat
    command: ["filebeat", "-e", "-c", "/opt/filebeat/filebeat.yml", "-d"]


  logstash:
    depends_on:
      filebeat:
        condition: service_healthy
    image: docker.elastic.co/logstash/logstash:8.11.1
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/config/logstash.conf
      - ./:/opt/logstash
    command: ["logstash", "-f", "/usr/share/logstash/config/logstash.conf"]



  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch-docker_cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
      - ELASTICSEARCH_NODE_PORT=9200
      - ELASTICSEARCH_NODE_HTTP_TYPE=http
      - bootstrap.memory_lock=false
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - 9200:9200
    networks:
      - elastic


  kibana:
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    environment:
      - node.name=kibana
      - cluster.name=elasticsearch-docker_cluster
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elastic

networks:
  elastic:
    driver: bridge