version: "3.8"
services:

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.1
    container_name: filebeat


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch-docker_cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
      - ELASTICSEARCH_NODE_PORT=9200
      - ELASTICSEARCH_NODE_HTTP_TYPE=http
      - bootstrap.memory_lock=false
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"